#include <stdio.h>
#include <stdlib.h>

// Links to closure entry points for the purpose of inspecting
// any structures that are allocated on the heap.

extern int* TOP();

// A simple, non-collected heap:
#define HEAPLEN 64000
int freeHeap = 0;
int heap[HEAPLEN];

/***
 * Stop execution and exit.  Not necessarily an error so exit with 0.
 ***/
void halt()
{
  printf("Halting.");
  exit(0);
}

/***
 * Print an error message and exit with 1. Runtime support function
 * for errors generated by the program.
 ***/
void error(char * msg)
{
  fprintf(stderr, "Error: %s", msg);
  exit(1);
}

/***
 * Uses the value found one word behind the pointer given to allocate
 * an object in the heap. Writes the value found at f (a tag or
 * address) into the the first word of the object.  Returns the
 * address of the allocated object. 
 *
 * If there is not enough space in the heap, the program halts with
 * an error.
 ***/
int* alloc(int* f)
{
  int size = 1 + *(f - 1);
  if (size + freeHeap > HEAPLEN) {
    error("Out of memory!");
  }

  int* result = heap + freeHeap;
  *result   = (int)f;
  freeHeap += size;

  return result;
}

/***
 * Determines if the address given falls in the heap or not. If the
 * address is not in the heap, it must be a tag.
 ***/
int inHeap(int * start)
{
  return (*start) >= (int)heap && *(start) < (int) (heap + freeHeap);
}

/***
 * Prints the entire heap. Not currently used but useful for
 * debugging.
 ***/
void dumpHeap() {
  int i = 0;
  printf("Address   Contents\n");
  while (i<freeHeap) {
    int* start = heap+i;
    int* tag   = (int*)(*start);
    int  size  = *(tag - 1);
    int  isData = *(tag - 2);
    int* name  = (int *) *(tag - 3);
    i          = i + size + 1;
    if(isData)
      printf("%08x: [(%s)", start, name);
    else
      printf("%08x: [%08x ", start, *tag);

    while (size>0) {
      start++;
      if(inHeap(start))
        printf(" %08x", *start);
      else {
        // start - address of heap object
        // *start - heap object
        // **start - address stored at head of heap object
        // *** - info table about object
        tag = ((int *)*((int *) *start));
        name = (int *) *(tag - 3);
        printf(" %s", name);
      }
      size--;
    }
    printf("]\n");
  }
}

/***
 * Prints heap objects for the value given. Tags are recognized and
 * their names are printed. All pointers in the object are followed
 * until a tag is found.
 **/
void dumpValue(int * start) {
  
  int* tag   = (int*)(*start);
  int  size  = *(tag - 1);
  int  isData = *(tag - 2);
  int* name  = (int *) *(tag - 3);

  int * k = start;
  int j = size;
  while(j>0) {
    k++;
    if(inHeap(k))
      dumpValue((int *)*k);
    j--;
  }

  if(isData)
    printf("%08x: [(%s)", start, name);
  else
    printf("%08x: [%08x ", start, *tag);
  
  while (size>0) {
    start++;
    if(inHeap(start))
      printf(" %08x", *start);
    else {
      // start - address of heap object
      // *start - heap object
      // **start - address stored at head of heap object
      // *** - info table about object
      tag = ((int *)*((int *) *start));
      name = (int *) *(tag - 3);
      printf(" %s", name);
    }
    size--;
  }
  printf("]\n");
}

int main() {
    int* result;
    printf("Starting:\n");
    result = TOP();
    dumpValue(result);
    printf("Done: %d words allocated.\n",freeHeap);
    printf("Result Address = %08x\n", result);
    return 0;
}
