default: thesis.pdf

thesis.f.tex: thesis.tex preamble.tex
	lhs2tex --poly -o thesis.f.tex thesis.tex

frontmatter.f.tex: frontmatter.tex preamble.tex
	lhs2tex --poly -o frontmatter.f.tex frontmatter.tex

frontmatter.pdf: frontmatter.f.tex preamble.tex 
	pdflatex -interaction=batchmode -jobname="frontmatter" frontmatter.f.tex

languages.f.tex: languages.tex preamble.tex
	lhs2tex --poly -o languages.f.tex languages.tex

languages.pdf: languages.f.tex preamble.tex 
	pdflatex -interaction=batchmode -jobname="languages" languages.f.tex

thesis.pdf: thesis.f.tex frontmatter.f.tex preamble.tex languages.f.tex
	pdflatex -interaction=batchmode -jobname="thesis" thesis.f.tex
