default: thesis.pdf

frontmatter.pdf: frontmatter.f.tex preamble.tex 
	pdflatex -interaction=batchmode -jobname="frontmatter" frontmatter.f.tex

languages.pdf: languages.f.tex preamble.tex 
	pdflatex -interaction=batchmode -jobname="languages" languages.f.tex

thesis.pdf: thesis.f.tex frontmatter.f.tex preamble.tex languages.f.tex
	pdflatex -interaction=batchmode -jobname="thesis" thesis.f.tex

%.f.tex: %.tex 
	lhs2tex --poly -o $@ $<

%.pdf: %.f.tex 
	pdflatex -interaction=batchmode -jobname="$(basename @)" $<

